---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: docker-pv
  labels:
    type: local
    name: dockervolume
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/exports/data_ibmhlf14k8s/docker"

---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: docker-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  storageClassName: ""
  selector:
    matchLabels:
      name: dockervolume
