---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: docker-pv
  labels:
    type: nfs
    name: dockervolume
spec:
  capacity:
    storage: 20Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    path: /SL02SEV2127646_1/data01
    server: fsf-dal1201e-fz.adn.networklayer.com
    readOnly: false

---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: docker-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 20Gi
  storageClassName: ""
  selector:
    matchLabels:
      name: dockervolume